# Generated by Django 4.2.11 on 2024-07-04 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naran", models.CharField(max_length=200, null=True)),
                (
                    "seksu",
                    models.CharField(
                        choices=[("Mane", "Mane"), ("Feto", "Feto")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("husi_diresaun", models.CharField(max_length=200, null=True)),
                ("hela_fatin", models.CharField(max_length=200, null=True)),
                ("nu_kontaktu", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funcionariu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naran", models.CharField(max_length=200, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Mane", "Mane"), ("Feto", "Feto")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("data_moris", models.DateField(null=True)),
                ("hela_fatin", models.CharField(max_length=200, null=True)),
                (
                    "municipio",
                    models.CharField(
                        choices=[
                            ("Aileu", "Aileu"),
                            ("Ainaru", "Ainaru"),
                            ("Baucau", "Baucau"),
                            ("Bobonaru", "Bobonaru"),
                            ("Covalima", "Covalima"),
                            ("Dili", "Dili"),
                            ("Ermera", "Ermera"),
                            ("Likisa", "Likisa"),
                            ("Lautem", "Lautem"),
                            ("Manatuto", "Manatuto"),
                            ("Manufahi", "Manufahi"),
                            ("Oecusse", "Oecusse"),
                            ("Viqueque", "Viqueque"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("nu_kontaktu", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=200, null=True)),
                ("diresaun", models.CharField(max_length=200, null=True)),
                (
                    "tipu_user",
                    models.CharField(
                        choices=[
                            ("Funsionariu", "Funsionariu"),
                            ("recepsionit", "recepsionit"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asuntu", models.CharField(max_length=200, null=True)),
                ("data", models.DateField(null=True)),
                ("orashahu", models.TimeField(auto_now_add=True)),
                ("orastermina", models.TimeField()),
                ("fatinhasoru", models.CharField(max_length=200, null=True)),
                (
                    "hasorufuncionariu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.funcionariu",
                    ),
                ),
                (
                    "naranvisitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.visitor",
                    ),
                ),
            ],
        ),
    ]
