# Generated by Django 4.2.11 on 2024-07-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0005_alter_gymclass_fotografia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymclass",
            name="fotografia",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
